


#spring.data.mongodb.uri=mongodb://localhost:27017/journaldb?replicaSet=rs0


spring.data.mongodb.uri = mongodb+srv://Ansuman:0747@cluster0.hzne8mh.mongodb.net/journalApp?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.uri=mongodb+srv://Ansuman:0747@cluster0.hzne8mh.mongodb.net/journalApp?retryWrites=true&w=majority

#spring.security.user.name=admin
#spring.security.user.password=1234



spring.data.mongodb.auto-index-creation=true

#spring.data.mongodb.auto-index-creation=true
